name: Terraform
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
on: 
  # push:
  workflow_dispatch: 

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v3

            - name: Terraform fmt
              run: terraform fmt
            - name: Terraform Init
              run: terraform init

            - name: Terraform plan
              run: terraform plan

            - name: Terraform apply
              run: terraform apply -auto-approve

name: GCP Auth with OIDC
on:
    workflow_dispatch: 
jobs:
    gcp-oidc:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: 'google-github-actions/auth@v2'
              with:
                project_id: ${{ secrets.PROJECTID }}
                workload_identity_provider: ${{ secrets.workload_identity_provider }}
                service_account: ${{ secrets.service_account }}
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                version: '>= 363.0.0'